### ISSUE TITLE
自动审批收款的JOB有时不能自动审批，提示销售单状态错误

### ISSUE THREAD

**Issue by kingofhawks** [kingofhawks/yycoin#119]
2015-10-20 13:20:16]WARN  com.china.center.oa.finance.manager.impl.PaymentApplyManagerImpl$1.doInTransaction(Unknown Source) [org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-8] ErrorNumber is :销售单状态错误,请确认操作
ErrorNumber is :销售单状态错误,请确认操作
	at com.china.center.oa.finance.manager.impl.PaymentApplyManagerImpl.createInbillForJob(Unknown Source)
	at com.china.center.oa.finance.manager.impl.PaymentApplyManagerImpl.passPaymentApplyForJob(Unknown Source)
	at com.china.center.oa.finance.manager.impl.PaymentApplyManagerImpl$1.doInTransaction(Unknown Source)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:128)
	at com.china.center.oa.finance.manager.impl.PaymentApplyManagerImpl.passPaymentApplyJob(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor2173.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at $Proxy1039.passPaymentApplyJob(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor2172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:276)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:260)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:86)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)

**Comment by kingofhawks** [comment]
订单状态是保存或者驳回，就会报这个错。

smartman 2015/10/20 13:42:29
SO单的状态为0或者2
