### ISSUE TITLE
开票流程变更

### ISSUE THREAD

**Issue by kingofhawks** [kingofhawks/yycoin#169]
原流程是线下提供开票表格给财务，财务开完票后导入OA，生成开票申请及对应的出库单

新流程改为，商务批量导入开票需求，生成A开头的开票申请，财务批量导出开票申请开票，开完票，把发票号码导入系统

相当于当原来财务一步导入做的事，拆成两个部分，商务做一半，财务做另一半

系统更改：
1.在“中信销售”中增加“批量导入开票申请”导入功能，导入模板见附件，导入模板中，有一列虚拟发票号，默认为空，如多张销售单开一张发票，则在此列写入同一号码，生成开票申请时，则将多张销售单关联一个开票申请，否则一单一票，导入后，开票申请单状态为”待财务处理“，处理人员默认为”杨静“
2.在“资金管理”的”开票确认“功能中，增加 导出功能，导出查询结果，在查询条件中增加”开票状态“字段，导出内容见附件-》已有导出功能，不用新增了。
3.将现有”批量导入开票信息“功能更新，按新的模板导入，新模板只有两列：开票申请号与发票号码，导入后，将开票申请单状态变更为”结束“，并触发票随货发JOB-》在现有的批量修改发票号码功能上完善。

**Comment by kingofhawks** [comment]
批量开票查询和开票日志是否也要修改？

**Comment by kingofhawks** [comment]
第三步的事情能否就用现在的批量修改发票号码来做？原有的“批量导入开票信息”这功能就不用了

**Comment by kingofhawks** [comment]
1.导入开票申请后，确认开票或者审核页面都无法看到。
2. 查询条件加状态
3. 导入发票号码后，更新状态为结束。

**Comment by kingofhawks** [comment]
把销售单对应的商品和数量加入导出结果

**Comment by kingofhawks** [comment]
发票导出结果里有两个字段要调整下，你昨天增加的商品、数量、金额是抓的BASE表里的数据是吧

永银周苏东 2016/3/2 11:49:03
这样可能会引起财务误银，还是抓开票明细里的数量、金额吧

smartman 2016/3/2 11:50:37
是的。抓base表的数据
11:51:10
永银周苏东 2016/3/2 11:51:10
invoiceins_item，抓这张表里的吧

**Comment by kingofhawks** [comment]
开票申请的日志也有点问题，应该有两行时间，一行是导入生成开票申请的时间，一行是导入发票号，标记结束的时间

**Comment by kingofhawks** [comment]
SO单拆分时，T_CENTER_INVOICEINS这张表对的，item中数量和money不对

**Comment by kingofhawks** [comment]
开票还有几个小问题：
1.驳回时，可开票金额变为0，因为状态变成全部开票，也没法重新选择客户和销售单。应改为驳回时，开票状态变为可开票，可开票金额不为0，提交后，再把销售单的开票状态变为全部开票
2.2.退票通过后，不能把out表的invoicemoney字段值变成负的，最多变为0，如果只退部分发票，就只减去退票金额
永银周苏东 17:13:24 
批量审批的好了
永银周苏东 17:19:51 
还是加上数量吧，有可能会有除不尽的情况，只要导入时校验，同一销售单号累计的数量与开票金额与销售单总数量及金额相等即可

**Comment by kingofhawks** [comment]
对于合并开票，仍然取base表，对于拆分开票，根据导入商品+数量。

**Comment by kingofhawks** [comment]
导入开票申请时，如果输入虚拟发票号，之前会当作发票号写入T_CENTER_VS_INVOICENUM，现在是不是就不需要写入这张表了？应该在更新发票号码时，再写入此表吧。

**Comment by kingofhawks** [comment]
驳回之后销售单开票状态要改成未开票？开票金额呢

smartman 2016/3/3 17:16:28
退票是不是也只涉及销售单开票状态和金额要改？

永银周苏东 2016/3/3 17:17:07
不涉及状态，只涉及金额
17:17:38
smartman 2016/3/3 17:17:38
驳回吗？开票状态不变？

永银周苏东 2016/3/3 17:18:07
退票通过后，不能把out表的invoicemoney字段值变成负的，最多变为0，如果只退部分发票，就只减去退票金额，同时也减去base表中的invoicemoney的金额

永银周苏东 2016/3/3 17:18:30
驳回是要改状态的，我刚才说的是退票

永银周苏东 2016/3/3 17:18:48
驳回之后，一切归0，恢复到没有申请开票的状态

**Comment by kingofhawks** [comment]
导入时加个 紧急  字段吧

**Comment by kingofhawks** [comment]
不能把虚拟导入的发票号码写入这张表

smartman 2016/3/4 11:18:33
恩，这个也正想问你。

永银周苏东 2016/3/4 11:18:37
你写入了，JOB就认为这张票真开过票了

永银周苏东 2016/3/4 11:18:43
所以现在审批还是有问题的

smartman 2016/3/4 11:18:45
导入的时候，不能写入这个表了

smartman 2016/3/4 11:18:50
这个我马上改下

永银周苏东 2016/3/4 11:18:49
对

永银周苏东 2016/3/4 11:19:04
只有财务导入真实的发票号码才能写到这里

smartman 2016/3/4 11:19:09
以前导入的时候，这个就是发票号，现在导入的时候，这个虚拟发票号是没作用的

永银周苏东 2016/3/4 11:19:53
是的
11:20:18
永银周苏东 2016/3/4 11:20:18
只起到一个标识多张订单开一张票的标识作用

**Comment by kingofhawks** [comment]
导入的开票申请驳回后如何再次提交？

**Comment by kingofhawks** [comment]
退票按钮要用谁的权限登录才能出来？

**Comment by kingofhawks** [comment]
批量更新发票号码时，同一SO单开多张发票的情况无法导入

**Comment by kingofhawks** [comment]
退票功能在“销售管理”下边“申请退票”，最终是财务审批，还是在确认开票里确认退票

**Comment by kingofhawks** [comment]
导入开票申请后，base表的invoiceMoney已经设置好，为啥在通过申请时，还需要设置base表的invoiceMoney呢？

**Comment by kingofhawks** [comment]
昨天那个导入的问题，我看了下代码，觉得有点问题 。out表和base表中的invoiceMoney是否在导入申请后，就应该设置为对应的金额？

永银周苏东 2016/3/29 8:33:26
对

smartman 2016/3/29 8:33:43
在驳回后，out表的invoiceMoney被清0了，但是base表的invoiceMoney却没有清零

smartman 2016/3/29 8:33:58
这是一个问题，应该要清零的是吧

永银周苏东 2016/3/29 8:34:06
这样啊，我手工清掉再导看看

永银周苏东 2016/3/29 8:34:13
驳回时应该全部清零的

smartman 2016/3/29 8:34:23
恩，你看下对应base表的invoiceMoney

smartman 2016/3/29 8:35:04
还有一个问题，导入申请后已经设置了invoiceMoney,现在的代码在通过审核时，又设置了一次invoiceMoney，检查时就会报错“溢出xxx“，这个也是不需要了吧？
8:35:19
永银周苏东 2016/3/29 8:35:19
不需要

smartman 2016/3/29 8:35:42
只要在发起申请时，设置invoiceMoney，驳回时清零就行了。

**Comment by kingofhawks** [comment]
同一个SO单如果存在多个同一商品行，导入时T_CENTER_INVOICEINS_ITEM表的baseId会错误指向同一个。

**Comment by kingofhawks** [comment]
手工提交的开票申请，好像先到  开票稽核状态
2016/3/29 12:24:23
永银周苏东 2016/3/29 12:24:23
现在没地方处理开票稽核状态的开票申请了

smartman 2016/3/29 12:24:36
是的

永银周苏东 2016/3/29 12:25:31
改成提交 后到 待财务开票吧

**Comment by kingofhawks** [comment]
另：考虑增加一张表，记录已开票的开票申请单，如果票随货发状态为票随货发的，则不生成CK单，待订单出库时再一起生成CK单。如果状态是单独寄送的，则实时生成CK单

**Comment by kingofhawks** [comment]
如果同一个SO单，只有两个商品行是同一个productId，导入发票时，合并为1行，生成的item表中baseId为空。

**Comment by kingofhawks** [comment]
1.退票不能确认结束
2.退票没有把开票状态及开票金额更新

**Comment by kingofhawks** [comment]
在开票管理里，加个类型 查询条件

永银周苏东 2016/3/30 16:46:06


永银周苏东 2016/3/30 16:46:11
区分开票和退票

**Comment by kingofhawks** [comment]
驳回后，重新申请提交，销售单开票状态和金额不对。通过销售管理-》开票申请-》修改，重新提交。

**Comment by kingofhawks** [comment]
现在的正确做法应该是这样吧：
1. 导入开票申请的，直接就设置开票状态和金额
2. 手工提交申请的，是否也应该提交时就直接设置开票状态和金额？之前提交申请的时候不设置的

smartman 2016/3/31 12:29:02
就是在发起申请的时候，就应该设置开票状态和金额了，而不是在审批的过程中再设置

13:16:36
永银周苏东 2016/3/31 13:16:36
对

**Comment by kingofhawks** [comment]
退票，结束之后，实际应用是需要重新导入吗？
13:39:24
永银周苏东 2016/3/31 13:39:24
不管要不要重新导入，退票时，把状态置为0，金额-退票金额

smartman 2016/3/31 13:39:41
恩

永银周苏东 2016/3/31 13:40:00
然后提交时再检查是否开票金额=销售金额，等于就把开票状态置为1，更新开票金额

永银周苏东 2016/3/31 13:40:10
驳回也一样

**Comment by kingofhawks** [comment]
退票驳回OK了

永银周苏东 2016/3/31 15:25:55
但退票被批量通过到 待财务确认 状态，怎么通过啊，当时想简单了，没考虑退票类型的通过结束

smartman 2016/3/31 15:26:53
你是说批量审批了？

永银周苏东 2016/3/31 15:27:02
对
15:27:52
smartman 2016/3/31 15:27:52
现在退票的流程，系统中如果手工提交后，结束只有一步。待财务开票，确认后就结束了。

smartman 2016/3/31 15:28:28
要不改成如果是退票的批量审批，就直接批量结束？

永银周苏东 2016/3/31 15:28:31
要不限制批量审批只审批正向开票的开票申请，不处理  退票的状态

永银周苏东 2016/3/31 15:28:34
不行

smartman 2016/3/31 15:28:51
那也行，批量退票不处理退票吧

smartman 2016/3/31 15:28:59
批量审批不处理退票

永银周苏东 2016/3/31 15:28:59
好

永银周苏东 2016/3/31 15:29:16
对

**Comment by kingofhawks** [comment]
我知道了，手工提交的时候，应该没有写这个zzsInfo栏位

smartman 2016/3/31 16:40:39
就是这个问题导致的

smartman 2016/3/31 16:40:52
我栏位放大到1024了

永银周苏东 2016/3/31 16:40:57
好的

smartman 2016/3/31 16:41:27
你看 后边是否手工增加时，也要把这个栏位加上，现在并不填写的

永银周苏东 2016/3/31 16:41:39
加上吧

smartman 2016/3/31 16:41:43
恩

**Comment by kingofhawks** [comment]
不是，我指销售单

永银周苏东 2016/3/31 16:45:10
如果是有关联的开票申请，不能驳回吧

永银周苏东 2016/3/31 16:45:21
帮我确认下，要是能驳回得改掉

smartman 2016/3/31 16:45:42
销售单那个我来看看，只要提交了开票申请，就不能驳回吗？

永银周苏东 2016/3/31 16:45:41
不检查开票状态，检查开票金额，只要大于0，就不能驳回

smartman 2016/3/31 16:45:46
好

永银周苏东 2016/3/31 16:45:48
对

**Comment by kingofhawks** [comment]
开票申请提交有个BUG，现在只控制数量不大于销售数量，但按我们之前定的，是批量开票必须一次性开完是吗

永银周苏东 2016/4/7 10:06:03
那样的话得检查开票申请提交时，商品数量及总价必须等于销售单商品数量及总价
10:07:01
smartman 2016/4/7 10:07:01
恩，也可以。导入开票申请时，商品数量和总价必须与实际保持一致

永银周苏东 2016/4/7 10:07:11
嗯

**Comment by kingofhawks** [comment]
那个开票结束CK单的问题，是要改那个JOB吗？写入preconsign表还是不变吧？

永银周苏东 2016/4/14 14:20:04
嗯，根据票随货发的状态位判断开票结束后，是直接写入preconsign表，还是等货的订单在库管审批通过后，再一起写入preconsign表

永银周苏东 2016/4/14 14:20:37
就是要增加一张临时表，来存储开票结束的开票申请号
14:21:19
smartman 2016/4/14 14:21:19
现在流程应该是这样的：
发票导入号码后就进入preconsign表，然后JOB不管票随货发状态，都是生成CK单。如果对应SO单已出库，就合并CK单

smartman 2016/4/14 14:23:04
写入preconsign表，不是JOB做的事情。是在导入发票号码时写入的
14:23:58
永银周苏东 2016/4/14 14:23:58
对，所以要在发票导入号码后，做判断
14:35:40
smartman 2016/4/14 14:35:40
1. 导入发票号码时，如果票随货发，就不写入preconsign表，写入临时表
2. 如果非票随货发，就写入preconsign表
3. SO单库管审核通过时，需要检查临时表，有的话就写入两条preconsign，并且把临时表删除
是这样吗？

永银周苏东 2016/4/14 14:36:00
对的

smartman 2016/4/14 14:36:58
现在的流程问题是，如果票随货发，也直接写入preconsign，并且生成CK单了，但是SO单没有生成CK单，所以发票会单发？

永银周苏东 2016/4/14 14:37:19
对
14:37:56
永银周苏东 2016/4/14 14:37:56
还有个判断，如果是票随货发，但货的订单已经库管审批通过，那发票也直接写入preconsign

smartman 2016/4/14 14:38:54
导入发票号码的时候，对应的SO单还没有库管审批通过吗？

smartman 2016/4/14 14:39:25
能否在导入发票号码的时候，限制SO单必须已出库？

永银周苏东 2016/4/14 14:39:28
不行

永银周苏东 2016/4/14 14:39:48
现在就有发票导入后，将关联订单自动审批通过的逻辑在
14:40:19
smartman 2016/4/14 14:40:19
恩，现在有个票随货发的JOB

永银周苏东 2016/4/14 14:41:02
对，加这段主要是现在都是在待库管审批状态才能提开票申请，现在已经放开到待商务审批就可以提，所以要保持一致节奏

smartman 2016/4/14 14:41:30
好，先这么改吧

永银周苏东 2016/4/14 14:41:32
好

**Comment by kingofhawks** [comment]
[2016-04-26 08:20:23]ERROR org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.fail(DependencyWaiterApplicationContextExecutor.java:432) [Timer-0] Unable to create application context for [com.china.center.oa.finance.inner], unsatisfied dependencies: Dependency on [(objectClass=com.china.center.oa.sail.dao.TempConsignDAO)] (from bean [&tempConsignDAO])

org.springframework.context.ApplicationContextException: Application context initialization for 'com.china.center.oa.finance.inner' has timed out

	at org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:462)

	at org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:51)

	at org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:108)

	at java.util.TimerThread.mainLoop(Unknown Source)

	at java.util.TimerThread.run(Unknown Source)

[2016-04-26 08:20:23]ERROR org.springframework.osgi.extender.internal.support.DefaultOsgiBundleApplicationContextListener.onOsgiApplicationEvent(DefaultOsgiBundleApplicationContextListener.java:50) [Timer-0] Application context refresh failed (OsgiBundleXmlApplicationContext(bundle=com.china.center.oa.finance.inner, config=application/applicationContext_*.xml))
