### ISSUE TITLE
中原银行邮件订单

### ISSUE THREAD

**Issue by kingofhawks** [kingofhawks/yycoin#272]
1.交易代码：890010:贵金属购买
2.公司名称：永银文化创意产业发展有限公司
3.返回信息：交易成功
4.交易状态：S:成功
另外交易机构的空格键需去除

永银周苏东 2016/7/8 14:46:54
这是中原银行的模板

永银周苏东 2016/7/8 14:47:03
1到4是筛选条件

smartman 2016/7/8 14:47:29
满足1-4的，才生成订单吗？

永银周苏东 2016/7/8 14:47:40
对，才是我们公司的订单

smartman 2016/7/8 14:48:35
那excel里边的记录都要保存吗？还是只满足条件才保存
14:48:49
永银周苏东 2016/7/8 14:48:49
满足条件的才保存

smartman 2016/7/8 14:48:55
好的

永银周苏东 2016/7/8 14:49:00
字段对应关系我一会发你

smartman 2016/7/8 14:49:21
恩

**Comment by kingofhawks** [comment]
中原银行的客户姓名规则是什么？


永银周苏东 2016/7/11 15:43:24
和招商一样，把交易机构字段中文前面的字符去掉

永银周苏东 2016/7/11 15:43:31
后缀加  -银行

永银周苏东 2016/7/11 15:43:39
把空格什么的都去掉

smartman 2016/7/11 15:44:02
好的

**Comment by kingofhawks** [comment]
读取邮件附件时报错
java.io.IOException: No content
	at com.sun.mail.imap.IMAPInputStream.fill(IMAPInputStream.java:111)
	at com.sun.mail.imap.IMAPInputStream.read(IMAPInputStream.java:158)
	at com.sun.mail.imap.IMAPInputStream.read(IMAPInputStream.java:184)
	at com.sun.mail.util.BASE64DecoderStream.getByte(BASE64DecoderStream.java:337)
	at com.sun.mail.util.BASE64DecoderStream.decode(BASE64DecoderStream.java:230)
	at com.sun.mail.util.BASE64DecoderStream.read(BASE64DecoderStream.java:135)
	at jxl.read.biff.File.<init>(File.java:110)
	at jxl.Workbook.getWorkbook(Workbook.java:257)
	at jxl.Workbook.getWorkbook(Workbook.java:242)
	at com.center.china.osgi.publics.file.read.MyXLSReader.readFile(MyXLSReader.java:117)
	at com.china.center.oa.sail.manager.impl.ImapMailClient.parseZyOrder(ImapMailClient.java:2149)
	at com.china.center.oa.sail.manager.impl.ImapMailClient.parseMultipart(ImapMailClient.java:1369)
	at com.china.center.oa.sail.manager.impl.ImapMailClient.receiveEmail(ImapMailClient.java:266)
	at com.china.center.oa.sail.manager.impl.ImapMailClient.main(ImapMailClient.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

**Comment by kingofhawks** [comment]
yinlujie@yycoin.com

smartman 2016/7/12 15:11:58
恩，你转发一封中原的上去看看呢，昨天我测试发现有点问题

永银周苏东 2016/7/12 15:12:06
好

smartman 2016/7/12 15:12:10
中原的固定用这个邮件地址吗？

永银周苏东 2016/7/12 15:12:18
昨天说的几个点都在这个包里改过了吧

永银周苏东 2016/7/12 15:12:27
对

**Comment by kingofhawks** [comment]
中原银行的单价取值要修改下，不能直接取订单文件里的单价，要用金额/数量=单价
10:04:10
永银周苏东 2016/7/19 10:04:10
今早有邮件生成后，邮件没有标识已读，不断的生成OA单号
